import "./globals.css";
import type { Metadata } from "next";

import { Open_Sans } from "next/font/google";
import { cn } from "@/libs/utils";

import Navbar from "@/components/Navbar";

const open = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(open.className, "bg-[#19142A]")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

export const revalidate = 0;
