import { cn } from "@/libs/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const open = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          open.className,
          "bg-[#19142A] px-16 2xl:px-10  max-w-[1280px] m-auto"
        )}
      >
        {children}
      </body>
    </html>
  );
}
